---
name: Build GHOM

"on":
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'ghom'

jobs:
  build-ghom:
    runs-on: ubuntu-latest
    steps:
      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Build using buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/tibeer/ghom
          tags: ghcr.io/tibeer/ghom:latest
          containerfiles: |
            ./Containerfile

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
